// CREAR UN APLICACION QUE PERMITA CAMBIO DE MONEDA DE SOLES A DOLARES
// iNGRESAE U IMPORTE EN SOLES Y MUESTRE SU EQUIBVALENTE EN DOLARES

// CREAR UN APLICACION QUE PERMITA CAMBIO DE MONEDA DE DOLARES A SOLES
// iNGRESAE U IMPORTE EN DOLARES Y MUESTRE SU EQUIBVALENTE EN SOLES

function convetir (){
    let moneda=parseInt(document.getElementById("txtCantidad").value);

    
}